image: texlive/texlive:latest

LuaLaTeX:
  script:
    - latexmk -pdflua paper/thesis.tex
  artifacts:
    paths:
      - paper/thesis.pdf

XeLaTeX:
  script:
    - latexmk -pdfxe paper/thesis.tex
  artifacts:
    paths:
      - paper/thesis.pdf
