image: texlive/texlive:latest

LuaLaTeX:
  script:
    - sed 's/\[czech/\[slovak/' thesis.tex > thesis-sk.tex
    - sed 's/\[czech/\[english/' thesis.tex > thesis-en.tex
    - latexmk -pdflua thesis.tex
    - latexmk -pdflua thesis-en.tex
    - latexmk -pdflua thesis-sk.tex
  artifacts:
    paths:
      - thesis.pdf
      - thesis-en.pdf
      - thesis-sk.pdf

XeLaTeX:
  script:
    - sed 's/\[czech/\[slovak/' thesis.tex > thesis-sk.tex
    - sed 's/\[czech/\[english/' thesis.tex > thesis-en.tex
    - latexmk -pdfxe thesis.tex
    - latexmk -pdfxe thesis-en.tex
    - latexmk -pdfxe thesis-sk.tex
  artifacts:
    paths:
      - thesis.pdf
      - thesis-en.pdf
      - thesis-sk.pdf
